In [77]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import html5lib

In [ ]:
import numpy as np
seasons = np.arange(9,21)

urls = []
for season in seasons:
    season_url = 'https://en.wikipedia.org/wiki/The_Bachelor_(season_{})'.format(season)
    urls.append(season_url)

In [62]:
def makeSoup(url):
    response=requests.get(url)
    soup=BeautifulSoup(response.content,"lxml")
    return soup

In [141]:
import re

def dataCollector(soup):
    # make the soup
    this = makeSoup(soup)
    
    # find the right table
    tables = this.findChildren('table')
    table = tables[1]
    
    # turn the data into a workable format
    data   = [[td.text for td in row.select('td')]
             for row in table.findAll('tr')]
    
    # create the header row and the body
    header = ['name','age', 'hometown', 'occupation', 'elimination']
    body = data[1:]
    cols   =  zip(*body)
    
    # create a dict with the data
    tbl_d  = {name:col for name, col in zip(header,cols)}
    
    # extract the season number from the original soup
    number = re.findall(r'\d+', soup)
    
    # remove brackets
    num= ''.join(number)
    
    # create a new key with season number value pairs
    tbl_d['season'] = [num] * len(dic['age'])
    
    # clean up the names 
    new_names = []
    for name in tbl_d['name']:
        cleaned_name = re.sub(r'\[\d+\]', ' ', name)
        new_names.append(cleaned_name)

    tbl_d['name'] = new_names
    
    # return the dict
    return tbl_d

In [155]:
dic = dataCollector('https://en.wikipedia.org/wiki/The_Bachelor_(season_18)')

In [156]:
pd.DataFrame(dic)

,age,elimination,hometown,name,occupation,season
0,26,Winner,"Kearney, Missouri",Nikki Ferrell,Pediatric Nurse,18
1,32,Runner-up,"Sacramento, California",Clare Crawley,Hairstylist,18
2,26,Quit in week 9,"Buckhead, Georgia",Andi Dorfman,Assistant District Attorney,18
3,32,Eliminated in week 8,"Martha's Vineyard, Massachusetts[a]",Renee Oteri,Real Estate Agent,18
4,24,Eliminated in week 7,"Lexington, Ohio",Chelsie Webster,Science Educator,18
5,29,Withdrew in week 7,"Ottawa, Ontario",Sharleen Joynt,Opera Singer,18
6,29,Eliminated in week 6,"Iowa City, Iowa",Kat Hurd,Medical Sales Representative/NBA Dancer,18
7,22[1],Eliminated in week 6,"Shelby Charter Township, Michigan",Cassandra Ferguson,Former NBA Dancer,18
8,26,Eliminated in week 5,"Orland Park, Illinois",Alli Restko,Nanny,18
9,25,Eliminated in week 5,"Litchfield, Illinois",Danielle Ronco,Psychiatric Nurse,18
10,27,Eliminated in week 5,"Conyers, Georgia",Kelly Travis,Dog Lover,18
11,27,Eliminated in week 4,"Forty Fort, Pennsylvania",Elise Mosca,First Grade Teacher,18
12,26,Eliminated in week 4,"Austin, Texas",Lauren Solomon,Music Composer,18
13,24,Eliminated in week 3,"Aurora, Illinois",Christy Hansen,Marketing Manager,18
14,25[2],Eliminated in week 3,"Santa Barbara, California","Lucy !Lucinda ""Lucy"" Aragon",Free Spirit,18
15,27,Eliminated in week 2,"Clermont, Florida",Amy Long,Local News Reporter,18
16,27,Eliminated in week 2,"Miami, Florida",Chantel Forrest,Account Manager,18
17,24,Eliminated in week 2,"Porto Alegre, Brazil",Victoria Lima,Legal Assistant,18
18,24,Eliminated in week 1,"Tampa, Florida",Alexis Morgado,Communications Director/NHL Ice Girl,18
19,31,Eliminated in week 1,"Apopka, Florida",Amy Jokinen,Massage Therapist,18
20,25,Eliminated in week 1,"Roanoke, Texas",Ashley Poe,Grade School Teacher,18
21,23,Eliminated in week 1,"Miami, Florida",Christine Llano,Police Support Specialist,18
22,23,Eliminated in week 1,"Rockford, Illinois",Kylie Lewis,Interior Designer,18
23,25,Eliminated in week 1,"Antelope Acres, California",Lacy Faddoul,Nursing Home Owner,18
24,25,Eliminated in week 1,"Edmond, Oklahoma",Lauren Higginson,Mineral Coordinator,18
25,25,Eliminated in week 1,"Wagener, South Carolina",Maggie Gantt,Personal Banker,18
26,26,Eliminated in week 1,"Sutter, California",Valerie Eredia,Personal Trainer,18

,age,elimination,hometown,name,occupation,season
0,25,Winner,"Dallas, Texas",Melissa Rycroft,Sales Representative,13
1,24,Runner-up,"Brookfield, Wisconsin",Molly Malaney,Department Store Buyer,13
2,29,Eliminated in week 7,"Peace River, Alberta",Jillian Harris,Interior Designer,13
3,24,Eliminated in week 6,"Carlsbad, California",Naomi Rose Crespo,Flight Attendant,13
4,34,Eliminated in week 5,"Huntsville, Alabama",Stephanie Hogan,Single Mother & Medical Marketing Rep.,13
5,27,Eliminated in week 4,"Marlboro, New Jersey",Lauren Wanger,Teacher,13
6,25,Eliminated in week 4,"Sewickley, Pennsylvania",Megan Parris,Single Mother and Lacrosse Coach,13
7,29,Eliminated in week 4,"Marshall, Missouri",Shannon Bair,Dental Hygienist,13
8,29,Eliminated in week 4,"Blue Island, Illinois","Nicole ""Nikki"" Kaapke",Administrative Assistant,13
9,25,Eliminated in week 3,"Monroe, Connecticut",Erica DeSimone,Account Executive,13
10,27,Eliminated in week 3,"Lee's Summit, Missouri",Kari Fajen,Account Executive,13
11,27,Eliminated in week 3,"Morton, Illinois",Natalie Getz,Human Resources Recruiter,13
12,27,Eliminated in week 2,"Recife, Pernambuco, Brazil",Raquel Medeiros,Medical Student,13
13,32,Eliminated in week 2,"Batavia, New York",Sharon Staebell,Teacher,13
14,28,Quit in week 2,"Boise, Idaho",Lisa Gonzalez,Public Relations Associate,13
15,24,Eliminated in week 1,"Phoenix, Arizona",Ann Lueders,Flight Attendant,13
16,26,Eliminated in week 1,"Mt. Carmel, Pennsylvania",Dominique Carta,Medical Sales Rep.,13
17,23,Eliminated in week 1,"Seattle, Washington",Emily,Casino Marketing Rep.,13
18,26,Eliminated in week 1,"Springfield, Massachusetts",Jackie Hickey,Wedding Coordinator,13
19,26,Eliminated in week 1,"Columbus, Ohio",Julie Dermotta,Teacher,13
20,25,Eliminated in week 1,"Calgary, Alberta",Nicole Mah,Menswear Buyer,13
21,36,Eliminated in week 1,"Southfield, Michigan",Renee Simlak,Jewelry Designer,13
22,23,Eliminated in week 1,"Stockton, California",Shelby,Account Executive,13
23,24,Eliminated in week 1,"Orem, Utah",Stacia Mann,Single Mother & Charity Accountant,13
24,28,Eliminated in week 1,"Salt Lake City, Utah",Treasure Morgan,Single Mother and Nurse Practitioner,13