In [77]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import html5lib

In [ ]:
import numpy as np
seasons = np.arange(9,21)

urls = []
for season in seasons:
    season_url = 'https://en.wikipedia.org/wiki/The_Bachelor_(season_{})'.format(season)
    urls.append(season_url)

In [62]:
def makeSoup(url):
    response=requests.get(url)
    soup=BeautifulSoup(response.content,"lxml")
    return soup

In [122]:
import re

def dataCollector(soup):
    this = makeSoup(soup)
    
    tables = this.findChildren('table')
    table = tables[1]
    
    data   = [[td.text for td in row.select('td')]
             for row in table.findAll('tr')]
    
    
    header = ['name','age', 'hometown', 'occupation', 'elimination']
    body = data[1:]
    cols   =  zip(*body)
    
    tbl_d  = {name:col for name, col in zip(header,cols)}
    
    number = re.findall(r'\d+', soup)
    
    # remove brackets
    num= ''.join(number)

    tbl_d['season'] = [num] * len(dic['age'])
    
    new_names = []
    for name in tbl_d['name']:
        cleaned_name = re.sub(r'\[\d+\]', ' ', name)
        new_names.append(cleaned_name)

    tbl_d['name'] = new_names
    
    return tbl_d

In [127]:
dic = dataCollector('https://en.wikipedia.org/wiki/The_Bachelor_(season_12)')

In [128]:
pd.DataFrame(dic)

,age,elimination,hometown,name,occupation,season
0,22,Winner,"Malibu, California",Shayne Lamas,Actress,12
1,25,Week 8,"Durango, Colorado",Chelsea Wanstrath,Pharmaceutical sales rep.,12
2,27,Week 7,"Niceville, Florida",Amanda Rantuccio,Account Executive,12
3,26,Week 6,"Loveland, Colorado",Noelle Drake,Photographer,12
4,27,Week 5,"Brooklyn, New York",Marshana Ritchie,Fashion designer,12
5,22,Week 5,"Holland, Michigan",Robin Canfield,Advertising coordinator,12
6,22,Week 4,"Jacksonville Beach, Florida",Ashlee Williss,Singer-songwriter,12
7,25,Week 4,"Hollywood, California",Kelly Duncan,Medical sales rep.,12
8,24,Week 4,"Suffield, Ohio",Holly Durst,Children's book author,12
9,22,Week 3,"Stockton, California",Amy,Nanny,12
10,33,Week 3,"Venice, California",Erin Storm,Hot-dog vendor,12
11,33,Week 3,"Dillsburg, Pennsylvania",Kristine Heffelfinger,Personal trainer,12
12,28,Week 2,"Syracuse, New York",Michelle P.,Administrative assistant,12
13,25,Week 2,"Oklahoma City, Oklahoma",Carri Perrier,Church marketing rep.,12
14,25,Week 2,"Seattle, Washington",Erin Harper,Event planner,12
15,24,Week 1,"Boise, Idaho",Alyssa,Biology student,12
16,26,Week 1,"LaFollette, Tennessee",Amanda Petterman,Law student,12
17,30,Week 1,"Washington, D.C",Denise,Attorney and former White House aide,12
18,24,Week 1,"Austin, Texas",Devon,Makeup artist,12
19,23,Week 1,"Tampa, Florida",Lesley Geyer,Youth minister,12
20,33,Week 1,"Laguna Niguel, California",Michele R.,Interior designer,12
21,30,Week 1,"Alamo, California",Rebecca,Attorney,12
22,26,Week 1,"Chicago, Illinois",Stacey Elza,Graduate student,12
23,23,Week 1,"Beverly Hills, California",Tamara,Cocktail waitress,12
24,33,Week 1,"San Francisco, California",Tiffany,Real estate marketing rep.,12

,age,elimination,hometown,name,occupation,season
0,25,Winner,"Dallas, Texas",Melissa Rycroft,Sales Representative,13
1,24,Runner-up,"Brookfield, Wisconsin",Molly Malaney,Department Store Buyer,13
2,29,Eliminated in week 7,"Peace River, Alberta",Jillian Harris,Interior Designer,13
3,24,Eliminated in week 6,"Carlsbad, California",Naomi Rose Crespo,Flight Attendant,13
4,34,Eliminated in week 5,"Huntsville, Alabama",Stephanie Hogan,Single Mother & Medical Marketing Rep.,13
5,27,Eliminated in week 4,"Marlboro, New Jersey",Lauren Wanger,Teacher,13
6,25,Eliminated in week 4,"Sewickley, Pennsylvania",Megan Parris,Single Mother and Lacrosse Coach,13
7,29,Eliminated in week 4,"Marshall, Missouri",Shannon Bair,Dental Hygienist,13
8,29,Eliminated in week 4,"Blue Island, Illinois","Nicole ""Nikki"" Kaapke",Administrative Assistant,13
9,25,Eliminated in week 3,"Monroe, Connecticut",Erica DeSimone,Account Executive,13
10,27,Eliminated in week 3,"Lee's Summit, Missouri",Kari Fajen,Account Executive,13
11,27,Eliminated in week 3,"Morton, Illinois",Natalie Getz,Human Resources Recruiter,13
12,27,Eliminated in week 2,"Recife, Pernambuco, Brazil",Raquel Medeiros,Medical Student,13
13,32,Eliminated in week 2,"Batavia, New York",Sharon Staebell,Teacher,13
14,28,Quit in week 2,"Boise, Idaho",Lisa Gonzalez,Public Relations Associate,13
15,24,Eliminated in week 1,"Phoenix, Arizona",Ann Lueders,Flight Attendant,13
16,26,Eliminated in week 1,"Mt. Carmel, Pennsylvania",Dominique Carta,Medical Sales Rep.,13
17,23,Eliminated in week 1,"Seattle, Washington",Emily,Casino Marketing Rep.,13
18,26,Eliminated in week 1,"Springfield, Massachusetts",Jackie Hickey,Wedding Coordinator,13
19,26,Eliminated in week 1,"Columbus, Ohio",Julie Dermotta,Teacher,13
20,25,Eliminated in week 1,"Calgary, Alberta",Nicole Mah,Menswear Buyer,13
21,36,Eliminated in week 1,"Southfield, Michigan",Renee Simlak,Jewelry Designer,13
22,23,Eliminated in week 1,"Stockton, California",Shelby,Account Executive,13
23,24,Eliminated in week 1,"Orem, Utah",Stacia Mann,Single Mother & Charity Accountant,13
24,28,Eliminated in week 1,"Salt Lake City, Utah",Treasure Morgan,Single Mother and Nurse Practitioner,13